version: '2.1'

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - 8000:8000
    command: npm start